services:
  fastify_hub:
    container_name: fastify_ts_hub
    build: .
    ports:
      - "${FASTIFY_PORT}:3000"
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
